// @generated by harness-llm — DO NOT EDIT.
// Regenerate: cargo test -p harness-llm --features ts -- --ignored generate_bindings
// The Rust wire types in crates/harness-llm/src/types.rs are the source of truth.

export type ChatMessage = { role: string, content?: MessageContent, tool_calls?: Array<ToolCall>, tool_call_id?: string, name?: string, };
export type MessageContent = string | Array<ContentPart>;
export type ContentPart = { "type": "text", text: string, } | { "type": "image_url", image_url: ImageUrl, } | { "type": "file", file: FileData, };
export type ImageUrl = { 
/**
 * An `http(s)` URL or a `data:<mime>;base64,<...>` URI.
 */
url: string, };
export type FileData = { filename: string, 
/**
 * A `data:<mime>;base64,<...>` URI carrying the document bytes.
 */
file_data: string, };
export type ToolCall = { id: string, type: string, function: FunctionCall, };
export type FunctionCall = { name: string, 
/**
 * Arguments as a JSON string (per the OpenAI tool-calling format).
 */
arguments: string, };
